/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.placement.client;

import com.placement.business.PlacementBLRemote;
import com.placement.business.RuleBLRemote;
import com.placement.client.dlgs.EditPlacementDialog;
import com.placement.entity.Placement;
import com.placement.entity.Rule;
import com.placement.utility.EJBWrapperFactory;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kemele
 */
public class PlacementsDialog extends javax.swing.JDialog {

    List<Placement> placements = null;
    Placement selectedPlacement = null;

    /**
     * Creates new form PlacementsDialog
     */
    public PlacementsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        placementsTable.setColumnSelectionAllowed(false);
        placementsTable.setCellSelectionEnabled(false);
        placementsTable.setRowSelectionAllowed(true);

        //mod.getColumn(0).setWidth(50);
        placements = new ArrayList<>();
        fillData();
    }

    private void fillData() {
        try {
            Vector all = prepareDataVector();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Vector prepareDataVector() {
        PlacementBLRemote placementBL = new EJBWrapperFactory().getPlacementBL();
        Vector all = new Vector();        
        NumberFormat fm = NumberFormat.getPercentInstance();
        DefaultTableModel model = (DefaultTableModel) placementsTable.getModel();
        model.setDataVector(new String[][]{}, new String[]{"ID", "Code", "Name",
            "College", "Ac. Year", "Rule"});
        placements = placementBL.getAll();     
        for (Placement u : placements) {
            Vector v = new Vector();
            v.add(u.getId());
            v.add(u.getCode());
            v.add(u.getName());
            v.add(u.getCollegeId().getName());
            v.add(u.getAcademicYear());            
            v.add(u.getRuleId().toString());
            model.addRow(v);
            all.add(v);
        }
        placementsTable.getColumnModel().getColumn(0).setMaxWidth(70);
        placementsTable.repaint();
        selectedPlacement = null;
        return all;
    }

    private void handleRowSelection() {
        int id = placementsTable.getSelectedRow();
        if (id > -1 && placements != null && placements.size() > 0) {
            selectedPlacement = placements.get(id);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        newBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        departmentsBtn = new javax.swing.JButton();
        studentsBtn = new javax.swing.JButton();
        makePlacementBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        placementsTable = new javax.swing.JTable();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Placements");

        title.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        title.setText("Placements");

        jPanel1.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        newBtn.setText("New");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        departmentsBtn.setText("Departments");
        departmentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentsBtnActionPerformed(evt);
            }
        });

        studentsBtn.setText("Students");
        studentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsBtnActionPerformed(evt);
            }
        });

        makePlacementBtn.setText("Make Placement");
        makePlacementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makePlacementBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(departmentsBtn)
                .addGap(18, 18, 18)
                .addComponent(studentsBtn)
                .addGap(27, 27, 27)
                .addComponent(makePlacementBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBtn)
                    .addComponent(editBtn)
                    .addComponent(removeBtn)
                    .addComponent(refreshBtn)
                    .addComponent(departmentsBtn)
                    .addComponent(studentsBtn)
                    .addComponent(makePlacementBtn))
                .addContainerGap())
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        placementsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Code", "Name", "College", "Ac. Year", "Rule"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        placementsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        placementsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                placementsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(placementsTable);
        placementsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(404, 404, 404)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeBtn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void placementsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placementsTableMouseClicked
        handleRowSelection();
    }//GEN-LAST:event_placementsTableMouseClicked

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        try{
            EditPlacementDialog dialog = new EditPlacementDialog(null, true, 0, this, selectedPlacement);
            dialog.setVisible(true);
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_newBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        try{
            if (selectedPlacement == null) {
                JOptionPane.showMessageDialog(this, "Please select row!", "Warrning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            EditPlacementDialog dialog = new EditPlacementDialog(null, true, 1, this, selectedPlacement);
            dialog.setVisible(true);
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
         try {
            if (selectedPlacement == null) {
                JOptionPane.showMessageDialog(this, "Please select row!", "Warrning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int selc = JOptionPane.showOptionDialog(this, "Are you sure?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
            if (selc == JOptionPane.YES_OPTION) {
                PlacementBLRemote plcBL = new EJBWrapperFactory().getPlacementBL();
                if (plcBL.delete(selectedPlacement.getId())) {
                    this.prepareDataVector();
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot remove placement!", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        this.prepareDataVector();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void departmentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentsBtnActionPerformed
         try{
             if (selectedPlacement == null) {
                JOptionPane.showMessageDialog(this, "Please select row!", "Warrning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            PlacementDepartmentsDialog dialog  = new PlacementDepartmentsDialog(null, true, this, selectedPlacement);
            dialog.setVisible(true);
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_departmentsBtnActionPerformed

    private void studentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsBtnActionPerformed
         if (selectedPlacement == null) {
                JOptionPane.showMessageDialog(this, "Please select row!", "Warrning", JOptionPane.WARNING_MESSAGE);
                return;
            }
         PlacementStudentsDialog dialog = new PlacementStudentsDialog(null,true, selectedPlacement);
         dialog.setVisible(true);
    }//GEN-LAST:event_studentsBtnActionPerformed

    private void makePlacementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makePlacementBtnActionPerformed
        if (selectedPlacement == null) {
                JOptionPane.showMessageDialog(this, "Please select row!", "Warrning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        MakePlacementDialog dialog = new  MakePlacementDialog(null, true, selectedPlacement);
        dialog.setVisible(true);
    }//GEN-LAST:event_makePlacementBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlacementsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlacementsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlacementsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlacementsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlacementsDialog dialog = new PlacementsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton departmentsBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton makePlacementBtn;
    private javax.swing.JButton newBtn;
    private javax.swing.JTable placementsTable;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton studentsBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
