/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.placement.client.dlgs;

import com.placement.business.DepartmentBLRemote;
import com.placement.business.DepartmentPlacementBLRemote;
import com.placement.client.PlacementDepartmentsDialog;
import com.placement.entity.Department;
import com.placement.entity.DepartmentPlacement;
import com.placement.entity.Placement;
import com.placement.utility.EJBWrapperFactory;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author kemele
 */
public class EditPlacementDeptsDialog extends javax.swing.JDialog {
    
    DepartmentPlacementBLRemote deptBL = null;
    Placement placement = null;
    List<Department> depts = null;
    PlacementDepartmentsDialog plcDialog = null;
    int type=0;
    DepartmentPlacement selectedDept = null;
    /**
     * Creates new form EditPlacementDeptsDialog
     */
    public EditPlacementDeptsDialog(java.awt.Frame parent, boolean modal,int type, Placement plc, DepartmentPlacement selectedDept, PlacementDepartmentsDialog dialog) {
        super(parent, modal);
        this.plcDialog = dialog;
        placement = plc;
        this.selectedDept = selectedDept;
        this.type = type;
        deptBL = new EJBWrapperFactory().getDepartmentPlacementBL();        
        initComponents();
        depts = new ArrayList<>();
        DepartmentBLRemote deptrbl = new EJBWrapperFactory().getDepartmentBL();
        depts = deptrbl.getAll();
        for(Department d: depts){
            deptsCmb.addItem(d);
        }
        if(type ==0){
            this.setTitle("Add new Department");
        }else{
            this.setTitle("Edit Department Capacity");
            deptsCmb.setSelectedItem(selectedDept.getDepartmentId());
            capacityTxt.setText(selectedDept.getCapacity()+"");
            maxViolationTxt.setText(selectedDept.getMaxViolation()+"");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        deptsCmb = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        capacityTxt = new javax.swing.JTextField();
        maxViolationTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Department capacity");
        setAlwaysOnTop(true);

        jLabel1.setText("Select department:");

        jLabel2.setText("Capacity:");

        jLabel3.setText("Max. Violation:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deptsCmb, 0, 234, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(capacityTxt)
                            .addComponent(maxViolationTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deptsCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(capacityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maxViolationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addBtn.setText("OK");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try{
            int capacity = Integer.parseInt(capacityTxt.getText());
            int max = Integer.parseInt(maxViolationTxt.getText());
            Department d =(Department) deptsCmb.getSelectedItem();
            
             if(type ==0){
                 selectedDept = new DepartmentPlacement();
                 selectedDept.setCapacity(capacity);
                 selectedDept.setMaxViolation(max);
                 selectedDept.setPlacementId(placement);
                 selectedDept.setDepartmentId(d);  
                 if(deptBL.save(selectedDept)){
                     plcDialog.prepareDataVector();
                     this.dispose();
                 }else{
                    JOptionPane.showMessageDialog(this, "Cannot save department data! \n Please review the information u provided!!","Error", JOptionPane.ERROR_MESSAGE);
                }
             }else{
                 selectedDept.setCapacity(capacity);
                 selectedDept.setMaxViolation(max);
                 selectedDept.setPlacementId(placement);
                 selectedDept.setDepartmentId(d);  
                 if(deptBL.update(selectedDept)){
                     plcDialog.prepareDataVector();
                     this.dispose();
                 }else{
                    JOptionPane.showMessageDialog(this, "Cannot save department data! \n Please review the information u provided!!","Error", JOptionPane.ERROR_MESSAGE);
                }
             }                        
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_addBtnActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField capacityTxt;
    private javax.swing.JComboBox deptsCmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maxViolationTxt;
    // End of variables declaration//GEN-END:variables
}
